# Augalų įvairovė



## Tobulas sodas

**Mimosa pudica** yra lengviau auginti negu žmonės perspėja - tik svarbu sėklas sodinti į indą, kuris turėtų drenažą (sėklos ir šaknys jautrios neoringai arba permirkusiai žemei). Sudygusios jos nėra reiklios - joms tinka augti tiesioginėje saulės šviesoje, jeigu jos pakanka, augalas turėtų sužydėti sezono pabaigoje. Mimozos jautrios saulės šviesos pokyčiams - jeigu staiga mimoza gauna per daug saulės šviesos po ilgo tarpo mažai šviesos, lapai gali nudegti. Kadangi mimozų judėjimo mechanizmas reikalauja kalio, kas dvi savaites verta tręšti pomidorų trąšomis.

**Lychnis viscaria** sintetina daug brasinosteroidų, kurie turi teigiamą poveikį ne tik sau, bet ir aplinkiniams augalams. Augalas daugiametis, auginti šiltnamyje.

Augalų hormonų galima įsigyti internete. Auksinas skatina tįsimą ir dediferencijuoja augalų ląsteles (lieka kaliusas), giberelino rūgštis skatina žydėjimą. Triacontanolis ir brasinolidas (brasinosteroidas) skatina bendrą augalo augimą. Triacontanolis taip pat skatina rožių stiebų šakojimąsi ties žeme.

