# Duobagyviai

Koralų sekcijos akvariumuose mane retai sužavi, bet o bet - ar žinojote, jog koralai priklauso tam pačiam tipui kaip ir medūzos, polipai ir anemonai? Kas iš viso yra anemonai? Dar geriau, tipas - duobagyviai - angliškai yra cnidaria, kilęs nuo lotyniško kniti - dilgelė. Bet yra dar viena potenciali kilmė iš žodžio "knisti" - to paties lietuviško/latviško žodžio. Be to, duobagyviai iš tikrųjų yra įdomūs - jie nusprendė, jog jie nori imituoti medžius ir turėti visą ekosistemą. Kiti gyvūnai - koralai yra gyvūnai - irgi nesibodi duobagyvių. Nedelsdami - nerkime gilyn!

Duobagyvius - stacionariuosius - galima prilyginti medžiams, nes kiekvienas koralas yra gyvas tik iš išorės. Po plonu, kelių ląstelių sluoksniu yra kalcifikuotas skeletas, kuris kiekvienais metais auga. Kai esi stacionari plėvelė, turi problemą - nebūtinai gali susirasti maisto ir nebūtinai tas maistas turės visas medžiagas, kurių reikės. Tai normalu - daug gyvūnų vykdo reikalingų molekulių sintezę. Bet duobagyviai savyje - savo vagose yra tuntas skirtingų bakterijų ir pirmuonių, be kurių duobagyvis neišgyventų. Tai mes turime visą ekosistemą mažame pakete.

Duobagyviai auga panašiai kaip medžiai - kiekvienais metais jie pagamina naują kalcio sluoksnį, dėl kurio koralas auga. Kiekvienais metais galima sekti ir carbon date'inti koralus.