# Fermentai

Fermentai tokie svarbūs ląstelės biologijoje, jog nebūtų visiškai netikslu apibūdinti ląstelę kaip fermentų telkinį apsuptą plazminės membranos. Fermentai atlieka svarbią funkciją - jie sumažina reakcijų aktyvacijos energiją, jog reakcijos, kurios įprastai vyktų pernelyg lėtai išlaikyti gyvybę, galėtų vykti sparčiai.

## Fermentų struktūra

Didžioji dalis fermentų yra baltymai (maža dalis yra ribozimai). Fermentai yra globulės formos ir visi turi bendrą dalį - aktyvųjį centrą. Aktyvusis centras yra fermento vieta, kurioje fermentas sąveikauja su molekule, kurios reakciją fermentas katalizuos. Įprastai tokia molekulė yra vadinama *substratu*. Substratas sąveikauja aktyviajame centre su fermentoje amino rūgščių šoninėmis grupėmis. Įprastai tokios sąveikos tikslas - sumažinti molekulės stabilumą. Mažiau stabili molekulė yra labiau linkusi sąveikauti su kitomis molekulėmis. Kaip radikalai yra itin reaktyvūs, panašiai suardytas kovalentinis ryšys skatins substratą sudaryti naujus ryšius.

Svarbu pabrėžti, jog fermentai skatina reakcijos vyksmą į abi puses - fermentas su substratu sudaro tarpinį produktą, kuris turi panašią tikimybę arba virsti atgal į fermentą ir substratą, arba virsti į fermentą ir produktą. Bet jeigu reakcijos gali vykti į abi puses, koks tikslas jas skatinti fermentais? Kadangi mūsų ląstelė produktus naudoja kitoms reakcijoms, dėl mažėjančios suvartojamo produkto koncentracijos, reakciją taps linkusi vykti į "dešinę" - arba produkto pusę. Paprasčiausias pavyzdys yra H2CO3 suskaldymas į H2O ir CO2. Kadangi CO2 yra dujos, kurios nuolat šalinamos iš mūsų organizmo, mūsų organizme bus mažesnė koncentracija CO2 ir didesnė koncentracija H2CO3. Dėl to reakcija bus palankesnė į skilimo pusę. Lygiai taip pat reakcija vyktų priešingai, jeigu substrato būtų mažiau.

## Fermentų funkcijos

Kadangi fermentai gali skatinti reakcijų vyksmą, kokias reakcijas fermentai įprastai skatina mūsų organizme?

```{r}

Funkcija <- c("Sintezė")
Reakcija <- c("Naujų molekulių susidarymas")
Pavyzyds <- c("Gliukozės 6 fosfatas")
Reakcija <- c("Gliukozė → Gliukozės-6-fosfatas")



```

