# Klausimai diskusijai

## Baltymai

1. Kokie yra baltymų struktūriniai lygiai?
2. Kokias funkcijas gali atlikti baltymai? Kokie yra kiekvienos funkcijos pavyzdžiai?

## Membraniniai kanalai

1. Kuo skiriasi amino rūgščių sekos, esančios kanalo viduje, išorėje transmembraniniame segmente ir išorėje?
2. Kokios molekulės gali judėti per membraninius kanalus?

Smulkios hidrofilinės molekulės: įprastai tai yra jonai, amino rūgštys ir gliukozė.

3. Kokiais būdais gali būti valdomi kanalai? Kokiose ląstelėse kiekvienu tipu valdomi kanalai gali būti randami?

Įtampa, ligandais, mechaniškai valdomi kanalai.

## Augalai

1.Kokie yra gaubtasėklių stiebo sluoksniai nuo išorės iki vidaus?

## Augalų hormonai

1. Kokios pagrindinės augalų hormonų kategorijos?

Auksinas, giberelinas, etilenas, abscisinė rūgštis, citokininai ir brasinosteroidai.

2. Koks auksino poveikis augalui?

Skatina ląstelių tįsimą, atverdamas protonų kanalus. Protonai aktyvina ekspansinus, kurie ardo sienelės celiuliozę. Ląstelės turgoras nebeturi pasipriešinimo, todėl ląstelė pradeda tįsti.

3. Koks giberelino poveikis augalui? Sėklai?

Augalui - skatina žydėjimą. Sėklai - skatina luobelę išskirti fermentus, kurie hidrolizuotų endospermo polimerus.

4. Koks etileno poveikis augalui? Vaisiui?

Skatina augalo trigubą atsaką: kamieno storėjimą, stiebo linkimą į kablio formą ir tįsimą suletėjimą.

5. Koks brasinosteroidų poveikis augalui?

* Kartu su auksinu skatina ląstelių tįsimą
* Skatina ląstelių senėjimą
* Skatina atsparumą sausroms, šalnoms ir ligoms
* Skatina žiedadulkių dulkiadaigio tįsimą

6. Koks abscisinės rūgšties (ABA) poveikis augalui?

Skatina žiotelių užsivėrimą. ABA skatina žiotelių ląsteles į išorę išskirti kalį, o kartu ir vandenį. Tai mažėja varstomųjų ląstelių turgoras ir žiotelė užsidaro.

7. Kokios citokininų funkcijos?

* Skatina ląstelių dalijimąsi
* Skatina žaizdų gijimą
* Jeigu koncentracija lygi auksino, skatina dalytis ląsteles
* Jeigu koncentracija mažesnė negu auksino, skatina formuotis šaknis
* Jeigu koncentracija didesnė negu auksino, skatina formuotis stiebus

## Bakterijos

1. Kokios yra bakterijų pagrindinės dalys?
2. Kas yra gram dažymas? Kuo skiriasi gram neigiamos ir gram teigiamos bakterijos?
3. Kokie yra antibiotikų veikimo mechanizmai? Kodėl antibiotikai įprastai nėra pavojingi žmogui?
4. Kokiais trimis mechanizmais bakterijos horizontaliai perduoda genetinę informaciją?
5. Kuo šie būdai yra susiję su atsparumu antibiotikams?


