# TODO

1. Male and dog fertility - related to plastics?
2. Ką skirtingi numeriai reiškia ant buteliukų?

# Plastikas

Myliu plastiką ir myliu jo pritaikymą - vandens buteliai, kateteriai, vamzdžiai ir vamzdeliai, konstrukcijos, čekiai. Plastikas yra _visur_ ir natūraliai iškyla klausimas - ar gali būti problemų dėl to? FDA 2012 m. uždraudė tam tikrus plastikus kūdikių buteliukų sudėtyje ir Europos chemikalų agentūra nurodė, jog bisfenolis A (BPA, apie jį vėliau)

Anksčiau šnekėjome apie hidrofobines molekules - riebalų rūgštis, vaškus, steroidinius hormonus, visą puokštę molekulių, kurioms reikia išskirtinių sąlygų funkcionuotų organizme. Daugiausia dėl to, jog hidrofobinės molekulės yra linkusios lengvai difunduoti. Dėl to taip sunku numalšinti aštrumą maiste - kapsacinas, kuris sukelia aštrumą, yra hidrofobiškas ir sunkiau nusiplauna su vandeniu.

Bet iš hidrofobinės kilmės mus supa ne tik kapsaicinas - turime aliejus, riebalus, alyvas ir...plastikus. Techniškai, plastikai yra hidrofobiški, tačiau taip pat jie yra ilgi, tarpusavyje susipynę polimerai. Jie neturi reikalo maišytis su riebalais - lygiai taip pat kaip krakmolas vangiai tirpsta vandenyje. Esame saugūs tuo atžvilgiu.

Aišku, visur yra niuansų ir prieš eidamas į juos iškart turiu perspėti - daugiausia tai pagrįsta principais ir sveikatos organizacijų rekomendacijomis. Nepanašu, jog tyrimai yra atlikti ištirti ekstremalius atvejus, panašiausia, jog plastikų naudojimas rizikos sveikatai nesukelia. Nebent, nežinau, gersite lydytą plastiką?

So, visų pirma, plastikai yra polimerai - jie turi sureaguoti tarpusavyje iš smulkesnių komponentų - monomerų - jog taptų modeliais, vamzdeliais ir visu kuo kitu. Kadangi tai chėminė reakcija, visada reikia atsiminti, jog kažkokia procentinė dalis bus likusi nesureagavusi ir ištirpusi plastike. Kai šnekame apie BPA patekimą į vandenį, mes turime omenyje ne patį tirpstantį plastiką - kas nenutinka, nes plastikas degraduoja šimtus metų - o nesureagavusius monomerus. Jie gali reaguoti su estrogeno receptoriais, bet jų afinitetas yra 1000 kartų mažesnis. Neįsivaizduoju, kiek reikia turėti kontakto su plastiku, jog pavyktų gauti didesnes koncentracijas negu tos, kurios yra kiekvieno iš mūsų organizme (įskaitant vyrų). 

Įveskime dar vieną vingį - jeigu bandytume sukurti plastiką, mes gautume kažką kieto ir trapaus. Ką daryti, jeigu nori plastiką suminkštinti? Įdėk plasticizuojančios (?) medžiagos. Tai yra hidrofobiška maža molekulė, kuri padidina plastiko...skystumą/tirštumą. Pridėk šiek tiek, gausi PVC vamzdžius, pridėk daugiau, gausi katetetį. Viskas paprasta ir smagu. Problema - tai smulki molekulė. Problema - gali išdifunduoti esant aukštai temperatūrai.

Tai kur visa problema? Tai negali mums kenkti - bet smulkus plastikas gali kenkti aplinkai. Augalai turbūt gali išgyventi savaime, bet gyvūnai - ypač tie, kurie minta filtruodami vandenį - susiduria su problemomis. 

Male and dog fertility?

# Plastikai

Plastikas - mylime, bet ir nekenčiame, galvodami, jog jis kenksmingas. Taip, jis yra kenksmingas, bet ne mums, o aplinkai. 






