# Skiepai

Visi esate girdėję apie skiepus ir ko gero galite paaiškinti, kodėl jie skirti. Bet iš paskutinių kelių metų anti-vakcinuotojų bangos aišku - nebūtinai yra aišku, kas yra vakcinos. Šiame skyriuje sužinosite apie vakcinas, jų pagrindinę sudėtį ir sukeltą atsaką organizme.

## Kas tai?

Vakcinos, technine prasme, yra preparatas, kuris suteikia aktyvų įgytą imunitetą jos gavėjui. Vakcinos sudėtyje yra medžiaga, kuri primena ligą sukeliantį mikroorganizmą. Medžiaga, šiuo atveju, platus terminas tyčia - tai gali būti arba silpna, arba nebeveikli užkrato versija, arba tik dalis paties užkrato. Pavyzdžiui, rotaviruso vakcinoje yra atenuotas (susilpnintas) rotavirusas, kuris vis dar gali daugintis, bet negali sukelti ligos. Vakcinose taip pat gali būti ir užmuštos bakterijos arba tik jų specifiniai antigenai (membranos lipidai arba baltymai), kurie sukelia imuninį atsaką.

Vakcinos veikia skatindamos imuninę sistemą išvystyti imunitetą. Jeigu jau skaitėte skyrių apie imuninę sistemą, jau galite įsivaizduoti, jog atsakui į vakciną reaguoja T atminties ląstelės, kuriuos skatina B limfocitus subręsti į plazmines ląsteles ir gaminti antikūnus. Kitą kartą, kai organizmas susidurs su tikruoju užkratu, kraujyje jau cirkuliuos antikūnai, kurie greitai neutralizuos infekciją.

Papildoma vakcinų sudėtis stimuliuoti imuninį atsaką.

Tiomersalio naudojimas

## Vakcinų tipai

## Vakcinos veikimo trukmė

## Vakcinų šalutiniai poveikiai

## Vakcinų ateitis